name: resume-system
services:
  resumego:
    image: resumego:latest
    container_name: my-resumego
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql-resume2
      - DB_PORT=3306
      - DB_USER=resume_user
      - DB_PASSWORD=resume_user123456 
      - JWT_KEY=winter-key 
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynet

  mysql:
    image: mysql:latest
    container_name: mysql-resume2
    restart: always
    ports:
      - "8083:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwt123456
      MYSQL_DATABASE: internship_manager
      MYSQL_USER: resume_user
      MYSQL_PASSWORD: resume_user123456 
    volumes:
      - mysql-resume:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "resume_user", "-presume_user123456 "]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: resume-nginx
    ports:
      - "8084:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynet
    restart: unless-stopped

volumes:
  mysql-resume:
    name: resume-mysql-data

networks:
  mynet:
    name: resume-network 