name: Build and Release Dist
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd frontend
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip dist/  # 将 dist 目录压缩为 zip 文件

      - name: Upload dist.zip
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
